const ACTION_TYPES = {
  LOADING_MOVIE_DETAILS: "LOADING_MOVIE_DETAILS",
  GET_MOVIE_DETAILS: "GET_MOVIE_DETAILS",
  SORT_BY_TITLE: "SORT_BY_TITLE",
  SORT_BY_RUNTIME: "SORT_BY_RUNTIME",
  SORT_BY_RATING:"SORT_BY_RATING",
  SORT_BY_RELEASE_DATE: "SORT_BY_RELEASE_DATE",
  FETCH_MOVIES: "FETCH_MOVIES",
  INIT_FETCH_MOVIES: "INIT_FETCH_MOVIES",
  FETCH_SEARCHED_MOVIES: "FETCH_SEARCHED_MOVIES",
  FETCH_SORTED_MOVIES: "FETCH_SORTED_MOVIES"
};

export default ACTION_TYPES;
